
// auth.js
export const ADMIN_SAVE_TOKEN = 'ADMIN_SAVE_TOKEN'
export const FETCH_ADMIN_USER = 'FETCH_ADMIN_USER'
export const FETCH_ADMIN_USER_SUCCESS = 'FETCH_ADMIN_USER_SUCCESS'
export const FETCH_ADMIN_USER_FAILURE = 'FETCH_ADMIN_USER_FAILURE'
export const ADMIN_UPDATE_USER = 'ADMIN_UPDATE_USER'
export const ADMIN_LOGOUT = 'ADMIN_LOGOUT'

